apiVersion: apps/v1
kind: Deployment
metadata:
  name: krakend-deployment
spec:
  selector:
    matchLabels:
      app: krakend
  replicas: 2
  template:
    metadata:
      labels:
        app: krakend
    spec:
      containers:
      - name: krakend
        image: dpalmasan/k8s-krakend:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        command: [ "/usr/bin/krakend" ]
        args: [ "run", "-d", "-c", "/etc/krakend/krakend.json", "-p", "8080" ]
        volumeMounts:
          - name: jwks
            mountPath: /etc/krakend/jwks.json
            subPath: jwks.json
            readOnly: true

      volumes:
        - name: jwks
          secret:
            secretName: jwks
            defaultMode: 0555